baseurl = "https://www.markstenglein.com"
languageCode = "en-us"
title = "Stenglein Projects"
theme = "hugo-ocelotsloth"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Mark Stenglein's home on the internet."
    footer = "&copy; [Mark Stenglein](https://www.markstenglein.com) 2016 -- 2019 | [Github](https://github.com/ocelotsloth) | [Unsplash](https://unsplash.com/ocelotsloth)"
